# Generated by Django 3.1.7 on 2021-05-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
