# Generated by Django 3.1.7 on 2021-05-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='your_comment',
            new_name='your_comments',
        ),
    ]
