# Generated by Django 3.1.7 on 2021-05-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_auto_20210527_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Origami', max_length=100),
        ),
    ]
