# Generated by Django 3.1.7 on 2021-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0012_auto_20210527_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default='Painting', related_name='cats', to='blogApp.Category'),
        ),
    ]
